# Site settings
title: TacoConf
email: agrc@utah.gov
description: TacoConf Stuff
baseurl: ""
url: "https://tacoconf.org"
highlighter: rouge
twitter_username: tacoconfslc
permalink: /:title/
production_url: 'https://tacoconf.org'
livereload: true
reload_port: 35729
analytics:
    google:
        tracking_id: 'UA-79438504-1'
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    hard_wrap: false
timezone: America/Denver
exclude:
    - "node_modules"
    - "scripts"
    - "Gemfile.lock"
    - "Gemfile"
    - "GruntFile.js"
    - "bower.json"
    - "package.json"
    - "*.bak"
    - "README.md"
    - "docker-compose.yml"
    - "LICENSE"
    - "CODE_OF_CONDUCT.md"
